# markdown: redcarpet
markdown: CommonMark 
permalink: /:categories/:title.html
lsi: false
# pygments:
rouge: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: Jaden 's Blog
description: Jaden's Blog, powered by Jekyll...
author: Jaden Lian

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
